package com.hsmc.wallet.core

import java.math.BigInteger

/**
 * Ristretto255 elliptic-curve operations (RFC 9496) as a faithful port of
 * `curve25519-dalek` 4.1.3 (the exact crate the HSMC Rust node uses), written with
 * [java.math.BigInteger] for auditability.
 *
 * Only the operations needed by the wallet address derivation are implemented:
 *  - scalar arithmetic mod L (the Ristretto group order),
 *  - Edwards-curve point double/add over GF(2^255-19) (a = -1),
 *  - scalar multiplication by the Ed25519 basepoint,
 *  - the Ristretto canonical encoding ([compress]).
 *
 * Every formula below is copied verbatim from dalek's `field.rs`, `edwards.rs` and
 * `ristretto.rs`; the known-answer tests in `HdKeysKatsTest` validate the whole chain
 * against vectors generated by the actual Rust crate, and the basepoint encodings
 * asserted there match the values published in RFC 9496.
 *
 * Performance is not a goal: a single address derivation takes a few milliseconds.
 */
object Ristretto255 {

    /** Prime field modulus p = 2^255 - 19. */
    val P: BigInteger = BigInteger.ONE.shiftLeft(255).subtract(BigInteger.valueOf(19))

    /** Ristretto group order L = 2^252 + 27742317777372353535851937790883648493. */
    val L: BigInteger = BigInteger.ONE.shiftLeft(252)
        .add(BigInteger("27742317777372353535851937790883648493"))

    /** Edwards curve constant d = -121665/121666 mod p. */
    val EDWARDS_D: BigInteger = {
        val inv = BigInteger.valueOf(121666).modInverse(P)
        val num = BigInteger.valueOf(121665).multiply(inv).mod(P)
        P.subtract(num).mod(P)
    }()

    /** 2d mod p (used by the point-addition formula). */
    val TWO_D: BigInteger = EDWARDS_D.shiftLeft(1).mod(P)

    /** sqrt(-1) mod p; the non-negative root (LSB 0), matching dalek's SQRT_M1. */
    val SQRT_M1: BigInteger = {
        val candidate = BigInteger.valueOf(2).modPow(
            P.subtract(BigInteger.ONE).shiftRight(2), // (p-1)/4
            P
        )
        require(candidate.multiply(candidate).mod(P) == P.subtract(BigInteger.ONE)) {
            "2^((p-1)/4) is not sqrt(-1) mod p"
        }
        makeNonNegative(candidate)
    }()

    /** 1/sqrt(a - d) mod p (a = -1), the "ristretto magic" INVSQRT_A_MINUS_D. */
    val INVSQRT_A_MINUS_D: BigInteger = {
        // a - d = -1 - d
        val aMinusD = P.subtract(BigInteger.ONE).subtract(EDWARDS_D).mod(P)
        val sqrt = sqrtModP(aMinusD)
        makeNonNegative(sqrt.modInverse(P))
    }()

    // ── Field helpers ─────────────────────────────────────────────────────────

    /** Canonical 32-byte little-endian encoding of a field element. */
    fun toBytes(v: BigInteger): ByteArray {
        val m = v.mod(P)
        val bytes = ByteArray(32)
        var value = m
        for (i in 0 until 32) {
            bytes[i] = value.and(BigInteger.valueOf(0xFF)).toInt().toByte()
            value = value.shiftRight(8)
        }
        return bytes
    }

    /** Parses a 32-byte little-endian value as a field element (reduced mod p). */
    fun fromBytesLE(bytes: ByteArray): BigInteger {
        require(bytes.size == 32) { "expected 32 bytes, got ${bytes.size}" }
        var v = BigInteger.ZERO
        for (i in 31 downTo 0) {
            v = v.shiftLeft(8).or(BigInteger.valueOf(bytes[i].toLong() and 0xFF))
        }
        return v.mod(P)
    }

    /** dalek `FieldElement::is_negative`: LSB of the canonical encoding. */
    fun isNegative(v: BigInteger): Boolean = v.mod(P).testBit(0)

    private fun makeNonNegative(v: BigInteger): BigInteger =
        if (isNegative(v)) P.subtract(v).mod(P) else v.mod(P)

    /** x^((p-5)/8) = x^(2^252 - 3) — dalek `FieldElement::pow_p58`. */
    private fun powP58(x: BigInteger): BigInteger =
        x.modPow(BigInteger.ONE.shiftLeft(252).subtract(BigInteger.valueOf(3)), P)

    /**
     * dalek `FieldElement::sqrt_ratio_i(u, v)`: returns sqrt(u/v) with sign normalized
     * to non-negative, when u/v is a quadratic residue. The `wasSquare` flag is ignored
     * (callers only use this for values known to be square).
     */
    fun sqrtRatioI(u: BigInteger, v: BigInteger): BigInteger {
        val v3 = v.multiply(v).mod(P).multiply(v).mod(P)
        val v7 = v3.multiply(v3).mod(P).multiply(v).mod(P)
        var r = u.multiply(v3).mod(P).multiply(u.multiply(v7).mod(P).let(::powP58)).mod(P)
        val check = v.multiply(r.multiply(r).mod(P)).mod(P)
        val flipped = check == P.subtract(u).mod(P)
        val flippedI = check == P.subtract(u).mod(P).multiply(SQRT_M1).mod(P)
        if (flipped || flippedI) {
            r = r.multiply(SQRT_M1).mod(P)
        }
        return makeNonNegative(r)
    }

    /** Square root of a quadratic residue mod p (for the two curve constants only). */
    private fun sqrtModP(alpha: BigInteger): BigInteger {
        // p ≡ 5 mod 8, so sqrt = alpha^((p+3)/8), adjusted by sqrt(-1) if needed.
        val root = alpha.modPow(P.add(BigInteger.valueOf(3)).shiftRight(3), P)
        return if (root.multiply(root).mod(P) == alpha) makeNonNegative(root)
        else makeNonNegative(root.multiply(SQRT_M1).mod(P))
    }

    // ── Edwards curve points (extended coordinates X:Y:Z:T, a = -1) ────────────

    /** Extended Edwards point; T = X*Y/Z (mod p). */
    data class EdPoint(val x: BigInteger, val y: BigInteger, val z: BigInteger, val t: BigInteger) {
        companion object {
            val IDENTITY = EdPoint(BigInteger.ZERO, BigInteger.ONE, BigInteger.ONE, BigInteger.ZERO)

            /** Ed25519 basepoint, the Ristretto basepoint (dalek RISTRETTO_BASEPOINT_POINT). */
            val BASE = EdPoint(
                x = BigInteger("15112221349535400772501151409588531511454012693041857206046113283949847762202"),
                y = BigInteger("46316835694926478169428394003475163141307993866256225615783033603165251855960"),
                z = BigInteger.ONE,
                t = BigInteger.ZERO
            ).normalize()
        }

        /** Brings coordinates into canonical field representation (needed for T of BASE). */
        fun normalize(): EdPoint {
            val tx = x.mod(P)
            val ty = y.mod(P)
            val tz = z.mod(P)
            return EdPoint(tx, ty, tz, tx.multiply(ty).mod(P).multiply(tz.modInverse(P)).mod(P))
        }

        /** dalek `EdwardsPoint::double` (projective formulas from `edwards.rs`). */
        fun double(): EdPoint {
            val a = x.multiply(x).mod(P)
            val b = y.multiply(y).mod(P)
            val c = z.multiply(z).mod(P).shiftLeft(1).mod(P)
            val h = a.add(b).mod(P)
            val e = h.subtract(x.add(y).mod(P).multiply(x.add(y).mod(P)).mod(P)).mod(P)
            val g = a.subtract(b).mod(P)
            val f = c.add(g).mod(P)
            return EdPoint(
                x = e.multiply(f).mod(P),
                y = g.multiply(h).mod(P),
                t = e.multiply(h).mod(P),
                z = f.multiply(g).mod(P)
            )
        }

        /** dalek `EdwardsPoint::add` (add-2008-hwcd-3 extended formulas for a = -1). */
        fun add(other: EdPoint): EdPoint {
            val a = y.subtract(x).mod(P).multiply(other.y.subtract(other.x).mod(P)).mod(P)
            val b = y.add(x).mod(P).multiply(other.y.add(other.x).mod(P)).mod(P)
            val c = t.multiply(TWO_D).mod(P).multiply(other.t).mod(P)
            val d = z.shiftLeft(1).mod(P).multiply(other.z).mod(P)
            val e = b.subtract(a).mod(P)
            val f = d.subtract(c).mod(P)
            val g = d.add(c).mod(P)
            val h = b.add(a).mod(P)
            return EdPoint(
                x = e.multiply(f).mod(P),
                y = g.multiply(h).mod(P),
                t = e.multiply(h).mod(P),
                z = f.multiply(g).mod(P)
            )
        }
    }

    /** Scalar multiplication by the basepoint: s*B for a 32-byte little-endian scalar. */
    fun scalarMultBase(scalarBytes: ByteArray): EdPoint {
        require(scalarBytes.size == 32) { "scalar must be 32 bytes" }
        var s = BigInteger.ZERO
        for (i in 31 downTo 0) {
            s = s.shiftLeft(8).or(BigInteger.valueOf(scalarBytes[i].toLong() and 0xFF))
        }
        s = s.mod(L)
        var result = EdPoint.IDENTITY
        for (bit in 255 downTo 0) {
            result = result.double()
            if (s.testBit(bit)) {
                result = result.add(EdPoint.BASE)
            }
        }
        return result
    }

    /**
     * dalek `RistrettoPoint::compress` (from `ristretto.rs`), ported verbatim.
     * Returns the canonical 32-byte Ristretto encoding of the point.
     */
    fun compress(point: EdPoint): ByteArray {
        val x = point.x
        val y = point.y
        var z = point.z
        val t = point.t

        val u1 = z.add(y).mod(P).multiply(z.subtract(y).mod(P)).mod(P)
        val u2 = x.multiply(y).mod(P)
        val invsqrt = sqrtRatioI(BigInteger.ONE, u1.multiply(u2.multiply(u2).mod(P)).mod(P))
        val i1 = invsqrt.multiply(u1).mod(P)
        var i2 = invsqrt.multiply(u2).mod(P)
        val zInv = i1.multiply(i2.multiply(t).mod(P)).mod(P)
        var denInv = i2

        val iX = x.multiply(SQRT_M1).mod(P)
        val iY = y.multiply(SQRT_M1).mod(P)
        val enchantedDenominator = i1.multiply(INVSQRT_A_MINUS_D).mod(P)

        val rotate = isNegative(t.multiply(zInv).mod(P))

        var outX = x
        var outY = y
        if (rotate) {
            outX = iY
            outY = iX
            denInv = enchantedDenominator
        }
        if (isNegative(outX.multiply(zInv).mod(P))) {
            outY = P.subtract(outY).mod(P)
        }
        var s = denInv.multiply(z.subtract(outY).mod(P)).mod(P)
        if (isNegative(s)) {
            s = P.subtract(s).mod(P)
        }
        return toBytes(s)
    }

    /**
     * Compressed Ristretto encoding of the basepoint (RFC 9496 test vector).
     * e2f2ae0a6abc4e71a884a961c500515f58e30b6aa582dd8db6a65945e08d2d76
     */
    fun basepointEncoding(): ByteArray = compress(EdPoint.BASE)

    /** Compressed encoding of 2*B (RFC 9496 test vector). */
    fun twoBasepointEncoding(): ByteArray = compress(EdPoint.BASE.add(EdPoint.BASE))
}
