[package]
name = "hsmc-rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
axum = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
reqwest = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
hsmc-core   = { path = "../hsmc-core" }
hsmc-p2p    = { path = "../hsmc-p2p" }
hsmc-crypto = { path = "../hsmc-crypto" }
hsmc-oracle = { path = "../hsmc-oracle" }
hsmc-starks = { path = "../hsmc-starks" }
hsmc-stablecoin = { path = "../hsmc-stablecoin" }
hsmc-vm = { path = "../hsmc-vm" }
hsmc-rollup = { path = "../hsmc-rollup" }

