import { describe, expect, it } from "vitest";
import { validateSecurityConfig } from "../server/config";

const strong = { jwtSecret: "j".repeat(40), apiKey: "a".repeat(40), dbEncryptionKey: "d".repeat(40) };
describe("production containment policy", () => {
  it("rejects missing, weak, and autogenerated secrets", () => {
    expect(() => validateSecurityConfig({ nodeEnv: "production", ...strong, tlsCert: "cert", tlsKey: "key", apiKeyAutogenerated: "true" })).toThrow();
    expect(() => validateSecurityConfig({ nodeEnv: "production", ...strong, jwtSecret: "dev", tlsCert: "cert", tlsKey: "key" })).toThrow();
    expect(() => validateSecurityConfig({ nodeEnv: "production", ...strong, dbEncryptionKey: undefined, tlsCert: "cert", tlsKey: "key" })).toThrow();
  });
  it("requires TLS or an explicitly trusted proxy", () => {
    expect(() => validateSecurityConfig({ nodeEnv: "production", ...strong })).toThrow(/TLS/);
    expect(() => validateSecurityConfig({ nodeEnv: "production", ...strong, trustTlsProxy: "true" })).not.toThrow();
  });
  it("does not permit a development bypass without explicit local flag", () => {
    expect(validateSecurityConfig({ nodeEnv: "development" })).toBeUndefined();
  });
});
