/** Centralized, fail-closed API server configuration. */
import { resolve } from "path";

const MIN_SECRET_LENGTH = 32;
const DEV_DEFAULTS = new Set(["change-me", "changeme", "development", "dev", "secret", "password", "hsmc-secret"]);

function requiredSecret(name: string, value: string | undefined, production: boolean): string {
  const secret = (value || "").trim();
  if (production && (secret.length < MIN_SECRET_LENGTH || DEV_DEFAULTS.has(secret.toLowerCase()) || /^(generated|auto|default)[-_]/i.test(secret))) {
    throw new Error(`[CONFIG] ${name} must be explicitly configured with a strong non-development value in production`);
  }
  return secret;
}

export type SecurityValidationInput = {
  nodeEnv?: string;
  jwtSecret?: string;
  apiKey?: string;
  dbEncryptionKey?: string;
  apiKeyAutogenerated?: string;
  localDev?: string;
  host?: string;
  tlsCert?: string;
  tlsKey?: string;
  trustTlsProxy?: string;
};

/** Pure startup policy used by the server and focused tests. Never generates or persists secrets. */
export function validateSecurityConfig(env: SecurityValidationInput): void {
  const production = (env.nodeEnv || "development") === "production";
  if (!production) return;
  requiredSecret("JWT_SECRET", env.jwtSecret, true);
  requiredSecret("HSMC_API_KEY", env.apiKey, true);
  requiredSecret("DB_ENCRYPTION_KEY", env.dbEncryptionKey, true);
  if (env.apiKeyAutogenerated === "true") throw new Error("[CONFIG] autogenerated HSMC_API_KEY is not permitted in production");
  const tlsConfigured = Boolean(env.tlsCert?.trim() && env.tlsKey?.trim());
  if (!tlsConfigured && env.trustTlsProxy !== "true") throw new Error("[CONFIG] production requires TLS_CERT/TLS_KEY or HSMC_TRUST_TLS_PROXY=true");
}

const nodeEnv = process.env.NODE_ENV || "development";
const isProduction = nodeEnv === "production";
const host = (process.env.HSMC_HOST || "127.0.0.1").trim();
const localDev = process.env.HSMC_LOCAL_DEV === "true";
validateSecurityConfig({
  nodeEnv, jwtSecret: process.env.JWT_SECRET, apiKey: process.env.HSMC_API_KEY,
  dbEncryptionKey: process.env.DB_ENCRYPTION_KEY, apiKeyAutogenerated: process.env.HSMC_API_KEY_AUTOGENERATED,
  localDev: process.env.HSMC_LOCAL_DEV, host, tlsCert: process.env.TLS_CERT, tlsKey: process.env.TLS_KEY,
  trustTlsProxy: process.env.HSMC_TRUST_TLS_PROXY,
});

if (localDev && !["127.0.0.1", "::1", "localhost"].includes(host)) {
  throw new Error("[CONFIG] HSMC_LOCAL_DEV=true requires loopback HSMC_HOST binding");
}

export const config = {
  nodeEnv, isProduction, host,
  port: parseInt(process.env.HSMC_PORT || "3001", 10),
  dbPath: process.env.HSMC_DB_PATH || "/home/team/shared/hsmc.db",
  corsOrigin: process.env.CORS_ORIGIN || "http://localhost:3000",
  tlsCert: process.env.TLS_CERT || "", tlsKey: process.env.TLS_KEY || "",
  usingTls: !!(process.env.TLS_CERT && process.env.TLS_KEY),
  trustTlsProxy: process.env.HSMC_TRUST_TLS_PROXY === "true",
  dbSecurityStrict: process.env.DB_SECURITY_STRICT === "true",
  jwtSecret: requiredSecret("JWT_SECRET", process.env.JWT_SECRET, isProduction),
  apiKey: requiredSecret("HSMC_API_KEY", process.env.HSMC_API_KEY, isProduction),
  dbEncryptionKey: requiredSecret("DB_ENCRYPTION_KEY", process.env.DB_ENCRYPTION_KEY, isProduction),
  jwtAutogenerated: false, apiKeyAutogenerated: false, dbEncryptionKeyAutogenerated: false,
  isDevMode: localDev && !isProduction && ["127.0.0.1", "::1", "localhost"].includes(host),
  stripeSecretKey: process.env.STRIPE_SECRET_KEY || "", stripePublishableKey: process.env.STRIPE_PUBLISHABLE_KEY || "",
  stripeWebhookSecret: process.env.STRIPE_WEBHOOK_SECRET || "",
  stripeMode: ((process.env.STRIPE_SECRET_KEY || "").startsWith("sk_live_") ? "live" : "test") as "live" | "test",
  telegramBotToken: process.env.TELEGRAM_BOT_TOKEN || "", whatsappPhoneNumberId: process.env.WHATSAPP_PHONE_NUMBER_ID || "",
  whatsappAccessToken: process.env.WHATSAPP_ACCESS_TOKEN || "", whatsappVerifyToken: process.env.WHATSAPP_VERIFY_TOKEN || "",
  whatsappWebhookPort: parseInt(process.env.WHATSAPP_WEBHOOK_PORT || "3002", 10), treasuryAddress: process.env.HSMC_TREASURY_ADDRESS || "",
};

export function authSummary() { return { mode: config.isDevMode ? "dev" as const : "api_key" as const, apiKeyConfigured: !!config.apiKey, apiKeyAutogenerated: false }; }
