/**
 * HSMC Network — Centralized Environment Configuration
 *
 * Single source of truth for all environment variable reads in the API server.
 * Responsibilities:
 *   - Read env vars with clear defaults
 *   - Auto-generate secrets (JWT_SECRET, HSMC_API_KEY, DB_ENCRYPTION_KEY) on
 *     first startup when not set, persist them to `.env`, and log warnings
 *   - Mark auto-generated API keys so the server can stay in DEV MODE when it
 *     was never given an explicit key (backward compatible with the dev server)
 *
 * Security rules:
 *   - Secrets are persisted ONLY to `.env` (gitignored) — never committed.
 *   - Auto-generation is disabled when NODE_ENV=test or HSMC_DISABLE_AUTOGEN=true
 *     (integration tests pass their own env).
 *   - A secret already present in the environment is NEVER overwritten.
 */
import { existsSync, readFileSync, writeFileSync } from "fs";
import { randomBytes } from "crypto";
import { resolve } from "path";

const ENV_PATH = resolve(process.cwd(), ".env");
const MIN_SECRET_LENGTH = 32; // hex-encoded random bytes → 64 chars

/** True when auto-generation/persistence must be skipped (tests, CI). */
function autogenDisabled(): boolean {
  return (
    process.env.NODE_ENV === "test" ||
    process.env.HSMC_DISABLE_AUTOGEN === "true"
  );
}

/** Generate a random hex secret (64 hex chars for 32 bytes). */
function randomSecret(bytes = 32): string {
  return randomBytes(bytes).toString("hex");
}

/**
 * Read a secret from the environment. If missing (or too short) and autogen is
 * enabled, generate one, persist it to `.env`, and log a warning.
 * If autogen is disabled, generate an ephemeral value in-memory so the server
 * still functions (JWT signing, API key auth), but do not persist.
 */
function ensureSecret(
  name: string,
  minLength: number,
  description: string,
  opts: { marker?: string } = {},
): { value: string; autogenerated: boolean } {
  const existing = (process.env[name] || "").trim();
  if (existing.length >= minLength) {
    return { value: existing, autogenerated: false };
  }

  const generated = randomSecret();
  process.env[name] = generated;

  if (autogenDisabled()) {
    console.warn(
      `[CONFIG] ⚠️  ${name} not set — using ephemeral generated value (not persisted). ` +
        `Set ${name} in .env for stability across restarts. (${description})`
    );
    return { value: generated, autogenerated: true };
  }

  persistEnvValue(name, generated);
  if (opts.marker) persistEnvValue(opts.marker, "true");
  console.warn(
    `[CONFIG] ⚠️  ${name} not set — auto-generated and saved to ${ENV_PATH}. ` +
      `(${description}) For production, set a strong value manually and remove the autogen marker.`
  );
  return { value: generated, autogenerated: true };
}

/**
 * Upsert `NAME=value` into the `.env` file, preserving all other lines.
 * Creates the file if it does not exist. Never touches tracked files.
 */
function persistEnvValue(name: string, value: string): void {
  try {
    let content = "";
    if (existsSync(ENV_PATH)) {
      content = readFileSync(ENV_PATH, "utf8");
    }
    const lines = content.split("\n");
    const idx = lines.findIndex((l) => l.startsWith(`${name}=`));
    const line = `${name}=${value}`;
    if (idx >= 0) {
      lines[idx] = line;
    } else {
      lines.push(line);
    }
    writeFileSync(ENV_PATH, lines.join("\n").replace(/\n+$/, "\n"), {
      mode: 0o600,
    });
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    console.warn(
      `[CONFIG] ⚠️  Could not persist ${name} to ${ENV_PATH}: ${msg} — value will be ephemeral this run.`
    );
  }
}

// ── Load & validate all configuration ─────────────────────────────────────────
const nodeEnv = process.env.NODE_ENV || "development";

const jwt = ensureSecret("JWT_SECRET", MIN_SECRET_LENGTH, "signs and verifies auth JWTs");
const apiKey = ensureSecret("HSMC_API_KEY", MIN_SECRET_LENGTH, "authenticates API clients", {
  marker: "HSMC_API_KEY_AUTOGENERATED",
});
const dbEncryptionKey = ensureSecret(
  "DB_ENCRYPTION_KEY",
  16,
  "derives the AES-256-GCM key for column-level encryption"
);

export const config = {
  /** Runtime environment: development | production | test */
  nodeEnv,
  /** Is this a production deployment? (NODE_ENV=production) */
  isProduction: nodeEnv === "production",

  // ── Server ────────────────────────────────────────────────────────────────
  port: parseInt(process.env.HSMC_PORT || "3001", 10),
  dbPath: process.env.HSMC_DB_PATH || "/home/team/shared/hsmc.db",
  corsOrigin: process.env.CORS_ORIGIN || "http://localhost:3000",
  tlsCert: process.env.TLS_CERT || "",
  tlsKey: process.env.TLS_KEY || "",
  usingTls: !!(process.env.TLS_CERT && process.env.TLS_KEY),
  dbSecurityStrict: process.env.DB_SECURITY_STRICT === "true",

  // ── Secrets (auto-generated & persisted to .env when unset) ──────────────
  jwtSecret: jwt.value,
  jwtAutogenerated: jwt.autogenerated,
  apiKey: apiKey.value,
  apiKeyAutogenerated: apiKey.autogenerated || process.env.HSMC_API_KEY_AUTOGENERATED === "true",
  dbEncryptionKey: dbEncryptionKey.value,
  dbEncryptionKeyAutogenerated: dbEncryptionKey.autogenerated,

  /**
   * DEV MODE = no operator-provided API key. In dev mode auth is not enforced;
   * in production it always is. A key that was auto-generated (persisted or
   * ephemeral) keeps the server in dev mode so the existing dev frontend
   * (which sends no API key) keeps working untouched. An operator who sets a
   * real HSMC_API_KEY (and removes the autogen marker) gets auth enforced.
   */
  isDevMode:
    nodeEnv !== "production" &&
    (apiKey.autogenerated || apiKeyAutogenMarker() || !apiKey.value),

  // ── Stripe (HSMCPay) ──────────────────────────────────────────────────────
  stripeSecretKey: process.env.STRIPE_SECRET_KEY || "",
  stripePublishableKey: process.env.STRIPE_PUBLISHABLE_KEY || "",
  stripeWebhookSecret: process.env.STRIPE_WEBHOOK_SECRET || "",
  stripeSimulationMode:
    process.env.STRIPE_SIMULATION_MODE === "true" || !process.env.STRIPE_SECRET_KEY,
  stripeMode: (() => {
    const sk = process.env.STRIPE_SECRET_KEY || "";
    return sk.startsWith("sk_live_") ? ("live" as const) : ("test" as const);
  })(),

  // ── Misc services ─────────────────────────────────────────────────────────
  telegramBotToken: process.env.TELEGRAM_BOT_TOKEN || "",
  whatsappPhoneNumberId: process.env.WHATSAPP_PHONE_NUMBER_ID || "",
  whatsappAccessToken: process.env.WHATSAPP_ACCESS_TOKEN || "",
  whatsappVerifyToken: process.env.WHATSAPP_VERIFY_TOKEN || "",
  whatsappWebhookPort: parseInt(process.env.WHATSAPP_WEBHOOK_PORT || "3002", 10),
  treasuryAddress: process.env.HSMC_TREASURY_ADDRESS || "",
};

function apiKeyAutogenMarker(): boolean {
  return process.env.HSMC_API_KEY_AUTOGENERATED === "true";
}

/** Human-readable auth summary for startup logs & /health */
export function authSummary(): { mode: "dev" | "api_key"; apiKeyConfigured: boolean; apiKeyAutogenerated: boolean } {
  return {
    mode: config.isDevMode ? "dev" : "api_key",
    apiKeyConfigured: !!config.apiKey,
    apiKeyAutogenerated: config.apiKeyAutogenerated,
  };
}
