package com.hsmc.wallet.core

import org.junit.Assert.assertEquals
import org.junit.Test

/**
 * Known-answer tests for the on-chain address derivation (HdKeys + Ristretto255 +
 * Keccak-256). Every expected value below was generated by the actual HSMC Rust
 * stack (curve25519-dalek 4.1.3 + sha3) running the node's own hd_keys.rs logic
 * (see the `hsmc-vectors` generator); the basepoint anchors additionally match the
 * values published in RFC 9496.
 *
 * These tests run on CI (testDebugUnitTest) and are the verification gate for the
 * BigInteger Ristretto port — there is no local JVM available during development.
 */
class HdKeysKatsTest {

    private fun ByteArray.hex(): String = joinToString("") { "%02x".format(it) }

    private val seedM12 = "5eb00bbddcf069084889a8ab9155568165f5c453ccb85e70811aaed6f6da5fc19a5ac40b389cd370d086206dec8aa6c43daea6690f20ad3d8d48b2d2ce9e38e4"
        .let { hexToBytes(it) }
    private val seedM24 = "408b285c123836004f4b8842c89324c1f01382450c0d439af345ba7fc49acf705489c6fc77dbd4e3dc1dd8cc6bc9f043db8ada1e243c4a0eafb290d399480840"
        .let { hexToBytes(it) }

    private fun hexToBytes(s: String): ByteArray =
        (0 until s.length step 2).map { s.substring(it, it + 2).toInt(16).toByte() }.toByteArray()

    @Test
    fun `ristretto basepoint encoding matches RFC 9496`() {
        assertEquals(
            "e2f2ae0a6abc4e71a884a961c500515f58e30b6aa582dd8db6a65945e08d2d76",
            Ristretto255.basepointEncoding().hex()
        )
    }

    @Test
    fun `ristretto 2B encoding matches RFC 9496`() {
        assertEquals(
            "6a493210f7499cd17fecb510ae0cea23a110e8d5b901f8acadd3095c73a3b919",
            Ristretto255.twoBasepointEncoding().hex()
        )
    }

    @Test
    fun `m12 master key matches node derivation`() {
        val (il, ir) = HdKeys.masterFromSeed(seedM12)
        assertEquals("8ada1517f1ac5b2a420c66d2b44e581d8952be2e3ccc32be4bdbd45858f3edd0", il.hex())
        assertEquals("905d7f324bc8657cd8fd0a76b8a95e8fdd5a8b3a2de9c04d15a3717e89c10fb3", ir.hex())
    }

    @Test
    fun `m12 full path derivation matches node`() {
        // m/44'/8888'/0'/0/0 — every intermediate scalar asserted against the
        // reference output so a regression is pinpointed, not just the final address.
        var (sk, cc) = HdKeys.masterFromSeed(seedM12)
        assertEquals("8ada1517f1ac5b2a420c66d2b44e581d8952be2e3ccc32be4bdbd45858f3edd0", sk.hex())
        val steps = listOf(
            (44L + 0x80000000L) to "70fd8f961ade235c149022f3b19160a47b187bd8701aa9de0836a7f427cd8806",
            (8888L + 0x80000000L) to "de41e6fcca24464a37f43ff6bce3ee4489d9bd481e710df3872930aab6d2130e",
            (0L + 0x80000000L) to "cb76ef2a805a2a7ab98f0833df49c24034ab79f7b7d44605f4774bcb72fcc701",
            0L to "8463f9f5976d5d9188462e53c865eb0e5ff4309df424d03f5f43370f2a72cb07",
            0L to "3a4f3355f427131903a5b422f13ada4771fbf4b9ceb2f60cf8d0adeecc1fcd04"
        )
        for ((index, expectedSk) in steps) {
            val (nsk, ncc) = HdKeys.deriveChild(sk, cc, index)
            assertEquals(expectedSk, nsk.hex())
            sk = nsk
            cc = ncc
        }
        assertEquals(
            "16481690fc810181109345a9198da2c8431ff2728d77593f88d86d57f6940f5e",
            HdKeys.publicKeyBytes(sk).hex()
        )
    }

    @Test
    fun `m12 address matches node derivation`() {
        assertEquals(
            "HSMCaaa55b44346e1b0eac9457b484f63c0ba7755cb3",
            HdKeys.deriveAddress(seedM12)
        )
    }

    @Test
    fun `m24 full derivation matches node`() {
        val (il, ir) = HdKeys.masterFromSeed(seedM24)
        assertEquals("cafbb2af3615980b3e11ed756d28d899b33d318654897b79bfda4eee2ca24a6c", il.hex())
        assertEquals("2b7bd3676d5be971911cdafb1cf20cc4d8a0bc9e5a448862bbe4af03724e9e30", ir.hex())

        var (sk, cc) = HdKeys.masterFromSeed(seedM24)
        val steps = listOf(
            (44L + 0x80000000L) to "c41b626c317e205023e9f474714132941ec156cac06cb29cbf5ebb94347e3207",
            (8888L + 0x80000000L) to "9f254fe61bc049e72bf14626fa4e7936648aace859bd783f0c6afbf362e09002",
            (0L + 0x80000000L) to "a4bd4eb6ba6078be42e2523e1f0c925817cec3728ba57cc6bc4d29c6d947af07",
            0L to "c1f8260f48fbf58d1b8670e36fba1a75fc2d0d5a83161bf6e8e1fa144b580a00",
            0L to "f77e7d2dc5c380c63ea363b7bc5f6ab285425b5e61a34c8cd2b719aaa7448c00"
        )
        for ((index, expectedSk) in steps) {
            val (nsk, ncc) = HdKeys.deriveChild(sk, cc, index)
            assertEquals(expectedSk, nsk.hex())
            sk = nsk
            cc = ncc
        }
        assertEquals(
            "a448e79bc48d4b6fe8145f051d5e39ccda6b1f51585a4e573f99b143168ca511",
            HdKeys.publicKeyBytes(sk).hex()
        )
        assertEquals("HSMC8f08ac50f80ae4e20dc51e4b7e9e91a989abc688", HdKeys.deriveAddress(seedM24))
    }

    @Test
    fun `keccak256 matches the node digest`() {
        // keccak256("HSMC_ADDR_V2_" || m12_pubkey) — full 32 bytes from the reference.
        // Independently verified: pure-Python Keccak-256 (validated against
        // keccak256("") = c5d24601…) AND the Rust sha3 crate both produce
        // a0af5f3a5cea58906e5523d4aaa55b44346e1b0eac9457b484f63c0ba7755cb3.
        val pubkey = hexToBytes("16481690fc810181109345a9198da2c8431ff2728d77593f88d86d57f6940f5e")
        val full = HdKeys.keccak256("HSMC_ADDR_V2_".toByteArray() + pubkey)
        assertEquals(
            "a0af5f3a5cea58906e5523d4aaa55b44346e1b0eac9457b484f63c0ba7755cb3",
            full.hex()
        )
        // And the address is exactly hex(full[12..32]).
        assertEquals("aaa55b44346e1b0eac9457b484f63c0ba7755cb3", full.copyOfRange(12, 32).hex())
    }

    @Test
    fun `non-canonical master key is reduced, not rejected`() {
        // The m12 master IL is >= L (the node's from_canonical_bytes would panic on it).
        // The wallet must reduce mod L (correct BIP32 behavior) and still derive.
        val reduced = HdKeys.reduceScalar(HdKeys.masterFromSeed(seedM12).first)
        assert(reduced >= java.math.BigInteger.ZERO && reduced < Ristretto255.L)
        // Sanity: deriving still yields the expected address (already covered above).
        assertEquals("HSMCaaa55b44346e1b0eac9457b484f63c0ba7755cb3", HdKeys.deriveAddress(seedM12))
    }
}
