/**
 * Production-mode API Server helper for integration tests.
 *
 * Spawns the HSMC API server with NODE_ENV=production and an operator-provided
 * HSMC_API_KEY, so auth is enforced (unlike the dev-mode helper in
 * ./api-server.ts which leaves HSMC_API_KEY empty -> IS_DEV_MODE = true).
 *
 * Used by tests that must verify auth-gated routes, e.g. /node-proxy requiring
 * x-api-key in production (security review G6).
 */
import { spawn, type ChildProcess } from "node:child_process";
import { resolve } from "node:path";

const PROJECT_ROOT = resolve(import.meta.dirname, "../..");
const API_SERVER_PATH = resolve(PROJECT_ROOT, "server/api-server.ts");

// Unique port + DB so a prod-mode instance can run alongside the dev-mode
// instance (port 13337) in the same test process without clashing.
const PROD_PORT = parseInt(process.env.HSMC_PROD_TEST_PORT || "13338", 10);
const PROD_DB_PATH = process.env.HSMC_PROD_TEST_DB_PATH || "/tmp/hsmc-test-prod.db";

// Operator-provided key (>= MIN_SECRET_LENGTH=32) -> ensureSecret marks it
// autogenerated:false -> config.isDevMode = false -> auth enforced.
export const PROD_API_KEY = "hsmc-test-prod-api-key-0123456789abcdef";

let serverProcess: ChildProcess | null = null;
let baseUrl = `http://localhost:${PROD_PORT}`;

/**
 * Start the API server in production mode and wait until it's healthy.
 */
export async function startProdServer(): Promise<string> {
  if (serverProcess) {
    return baseUrl;
  }

  // Clean up any previous test DB
  try {
    const { unlink } = await import("node:fs/promises");
    await unlink(PROD_DB_PATH).catch(() => {});
    await unlink(PROD_DB_PATH + "-wal").catch(() => {});
    await unlink(PROD_DB_PATH + "-shm").catch(() => {});
  } catch { /* ignore */ }

  return new Promise((resolvePromise, reject) => {
    const env = {
      ...process.env,
      NODE_ENV: "production",
      HSMC_PORT: String(PROD_PORT),
      HSMC_DB_PATH: PROD_DB_PATH,
      HSMC_API_KEY: PROD_API_KEY,
      JWT_SECRET: "ci-test-jwt-secret-32bytes-minimum",
      DB_ENCRYPTION_KEY: "ci-test-db-encryption-key-16",
      // Do not persist auto-generated secrets into the repo .env during tests
      HSMC_DISABLE_AUTOGEN: "true",
    };

    serverProcess = spawn("bun", ["run", API_SERVER_PATH], {
      cwd: PROJECT_ROOT,
      env,
      stdio: ["ignore", "pipe", "pipe"],
    });

    let started = false;
    const timeout = setTimeout(() => {
      if (!started) {
        reject(new Error("Prod-mode API server failed to start within 15 seconds"));
      }
    }, 15000);

    serverProcess.stdout?.on("data", (data: Buffer) => {
      const output = data.toString();
      if (!started && output.includes("HSMC Local API server running")) {
        started = true;
        clearTimeout(timeout);
        // Give the server a brief moment to fully start
        setTimeout(() => resolvePromise(baseUrl), 500);
      }
    });

    serverProcess.stderr?.on("data", (data: Buffer) => {
      // Log stderr for debugging but don't fail — warnings are normal
      const msg = data.toString();
      if (!msg.includes("WARNING") && !msg.includes("⚠️")) {
        console.error("[api-server-prod stderr]", msg);
      }
    });

    serverProcess.on("error", (err) => {
      clearTimeout(timeout);
      reject(new Error(`Failed to spawn prod-mode API server: ${err.message}`));
    });

    serverProcess.on("exit", (code) => {
      if (!started) {
        clearTimeout(timeout);
        reject(new Error(`Prod-mode API server exited early with code ${code}`));
      }
    });
  });
}

/**
 * Stop the production-mode API server subprocess.
 */
export async function stopProdServer(): Promise<void> {
  if (serverProcess) {
    serverProcess.kill("SIGTERM");
    await new Promise((resolve) => setTimeout(resolve, 1000));
    if (serverProcess.exitCode === null) {
      serverProcess.kill("SIGKILL");
    }
    serverProcess = null;
  }

  // Clean up test DB files
  try {
    const { unlink } = await import("node:fs/promises");
    await unlink(PROD_DB_PATH).catch(() => {});
    await unlink(PROD_DB_PATH + "-wal").catch(() => {});
    await unlink(PROD_DB_PATH + "-shm").catch(() => {});
  } catch { /* ignore */ }
}

export function getProdBaseUrl(): string {
  return baseUrl;
}
